### ISSUE TITLE
Center the login page.

### ISSUE THREAD

**Issue by bencinn** [BenCinn/Node-Server#2]
I think the [Login Page](../tree/main/html/login.html) should be centered.

**Comment by bencinn** [comment]
Also the [Register Page](../tree/main/html/register.html) should be centered.

**Comment by BenCinn** [comment]
> Also the [Register Page](../tree/main/html/register.html) should be centered.

See #4

**Comment by bencinn** [comment]
> Also the [Register Page](../tree/main/html/register.html) should be centered.

See #5 for reference
